// build.rs
//
//! Generates compile-time configuration constants for procedural macros.
//!
//! IMPORTANT:
//! This file is executed at build time for the `macros-core` crate.
//! It reads selected values from the workspace `.env` file (or the process
//! environment) and emits a small Rust source file into `$OUT_DIR`.
//!
//! Only values that are required by procedural macros / build tooling
//! belong here. Runtime configuration continues to live in the `core`
//! crate and is loaded when the application starts.
//!
//! Do NOT edit the generated file by hand. Change the source of truth
//! (`.env` or the list of entries below) and rebuild.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    // Rebuild if the .env file changes.
    // We also rebuild if any of the specific environment variables change.
    println!("cargo:rerun-if-changed=build.rs");

    let workspace_root = find_workspace_root();
    let env_path = workspace_root.join(".env");

    if env_path.exists() {
        println!("cargo:rerun-if-changed={}", env_path.display());
        // Load .env into the current process environment so that
        // std::env::var can see the values.
        let _ = dotenvy::from_path(&env_path);
    }

    // ------------------------------------------------------------------
    // Compile-time configuration entries used by macros.
    //
    // To add a new constant:
    //   1. Add an entry to the list below.
    //   2. Document why the macro needs it at compile time.
    //   3. Rebuild. The constant will appear in the generated module.
    //
    // Format of each entry:
    //   (CONSTANT_NAME, ENV_KEY, default_value, rust_type, documentation)
    // ------------------------------------------------------------------
    let entries: &[(&str, &str, &str, &str, &str)] = &[
        (
            "FAKER_LOCALE",
            "APP_FAKER_LOCALE",
            "en",
            "&str",
            "Locale used by the Pawn factory macros (e.g. `::fake::faker::name::fa::Name`). \
             Only relevant at compile time for code generation.",
        ),
        // Example of a future entry:
        // (
        //     "SOME_OTHER_SETTING",
        //     "APP_SOME_OTHER_SETTING",
        //     "default_value",
        //     "&str",
        //     "Short explanation why this must be known at compile time.",
        // ),
    ];

    for (_, env_key, _, _, _) in entries {
        println!("cargo:rerun-if-env-changed={}", env_key);
    }

    let mut generated = String::new();
    generated.push_str("// @generated by macros-core/build.rs — DO NOT EDIT MANUALLY\n");
    generated.push_str("//\n");
    generated.push_str("// This file contains ONLY configuration values that procedural macros\n");
    generated.push_str("// need at compile time. It is regenerated on every build from the\n");
    generated.push_str("// workspace `.env` (or from the process environment).\n");
    generated.push_str("//\n");
    generated.push_str("// Runtime configuration lives in the `core` crate and is loaded when\n");
    generated.push_str("// the application starts. Do not mix the two.\n");
    generated.push_str("//\n");
    generated.push_str("// Changing any of these values requires a rebuild of crates that\n");
    generated.push_str("// depend on `macros-core`.\n\n");

    for (const_name, env_key, default, rust_type, doc) in entries {
        let value = env::var(env_key).unwrap_or_else(|_| default.to_string());

        // Escape the value so it is a valid Rust string literal.
        let escaped = value
            .replace('\\', "\\\\")
            .replace('"', "\\\"");

        generated.push_str(&format!("/// {}\n", doc));
        generated.push_str(&format!(
            "pub const {}: {} = \"{}\";\n\n",
            const_name, rust_type, escaped
        ));
    }

    let out_dir = env::var_os("OUT_DIR").expect("OUT_DIR not set");
    let dest = Path::new(&out_dir).join("build_config.rs");
    fs::write(&dest, generated).expect("failed to write build_config.rs");
}

/// Walks up from `CARGO_MANIFEST_DIR` until a `Cargo.toml` containing
/// `[workspace]` is found. This is the workspace root.
fn find_workspace_root() -> PathBuf {
    let mut dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set"));

    loop {
        let cargo_toml = dir.join("Cargo.toml");
        if cargo_toml.exists() {
            if let Ok(contents) = fs::read_to_string(&cargo_toml) {
                if contents.contains("[workspace]") {
                    return dir;
                }
            }
        }

        if !dir.pop() {
            // Fallback: treat the crate directory itself as root.
            // This keeps the build working even outside a workspace.
            return PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
        }
    }
}