use std::{env, fs, path::PathBuf};

fn main() {
    // -------------------------------------------------------------------------
    // Cargo build-script output directory.
    //
    // Generated files must live in OUT_DIR rather than inside src/.
    // This keeps the source tree user-owned and prevents build.rs from
    // modifying committed source files during a normal cargo build.
    // -------------------------------------------------------------------------
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is not set"));

    // =========================================================================
    // ---------------------------------------------
    //|          migration                         |
    // ---------------------------------------------
    // =========================================================================
    //
    // `registry.rs` is the single source of truth for enabled migrations.
    //
    // Example:
    //
    //     migration!(m_2025_01_15_1945_create_todos);
    //     migration!(m_2025_01_16_1030_create_users);
    //
    // Commenting out a declaration intentionally disables that migration.
    // build.rs never scans the filesystem to infer which migrations are active.
    //
    // The file is included into this function so `migration!` can simply push
    // the declared identifier into a normal Vec. This lets Rust's own parser
    // handle the source syntax; no regex, custom parser, or syn dependency is
    // required here.
    // -------------------------------------------------------------------------

    let mut migrations: Vec<&'static str> = Vec::new();

    let mut structs: Vec<&'static str> = Vec::new();
    macro_rules! migration {
        ($name:ident, $struct_name:ident) => {{
            migrations.push(stringify!($name));
            structs.push(stringify!($struct_name));
        }};
    }

    {
        include!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/src/migrations/registry.rs"
        ));
    }

    // Migration filenames contain a timestamp, so lexical ordering gives us
    // deterministic migration execution order regardless of declaration order
    // in registry.rs.
    migrations.sort_unstable();

    let mut generated = String::from(
        "// @generated by build.rs\n\
         //\n\
         // DO NOT EDIT.\n\
         //\n\
         // To add, remove, or disable migrations, edit:\n\
         //     src/migrations/registry.rs\n\
         //\n\
         // This file is generated automatically during the Cargo build.\n\
         \n",
    );

    // generated.push_str("use crate::migrator::Migration;\n\n");
    for migration in &migrations {
        let path = format!("{}/src/migrations/{}.rs", manifest_dir, migration);

        generated.push_str(format!("#[path = r\"{}\"]\n", path).as_str());
        generated.push_str(&format!("pub mod {};\n", migration));
    }

    generated.push_str(
        "\n\
         pub fn get_all_migrations() -> Vec<Box<dyn crate::migrator::Migration>> {\n\
         \tvec![\n",
    );

    for (index, migration) in migrations.iter().enumerate() {
        let current_struct = structs.get(index).unwrap();
        generated.push_str(&format!(
            "\t\tBox::new({}::{} ),\n",
            migration, current_struct
        ));
    }

    generated.push_str(
        "\t]\n\
         }\n",
    );

    fs::write(out_dir.join("migrations_generated.rs"), generated)
        .expect("failed to write generated migrations");

    // Only rerun this build script when the migration registry changes.
    println!("cargo:rerun-if-changed=src/migrations/registry.rs");

    // =========================================================================
    // ---------------------------------------------
    //|          seeder                            |
    // ---------------------------------------------
    // =========================================================================
    //
    // Seeder generation follows the same pattern as migrations:
    //
    //     let mut seeders = Vec::new();
    //
    //     macro_rules! seeder {
    //         ($name:ident) => {
    //             seeders.push(stringify!($name));
    //         };
    //     }
    //
    //     include!(concat!(
    //         env!("CARGO_MANIFEST_DIR"),
    //         "/src/seeders/registry.rs"
    //     ));
    //
    // The generated output should be written to:
    //
    //     $OUT_DIR/seeders_generated.rs
    //
    // Keep this section independent from migrations so each registry remains
    // explicit and independently controllable by the developer.
    // =========================================================================

    // =========================================================================
    // ---------------------------------------------
    //|          factory                            |
    // ---------------------------------------------
    // =========================================================================
    //
    // Factories use the same declaration -> build.rs -> generated Rust pattern.
    //
    //     factory!(user);
    //     factory!(post);
    //
    // The generated output should be written to:
    //
    //     $OUT_DIR/factories_generated.rs
    //
    // As with migrations and seeders, factory files are never discovered
    // automatically from the filesystem. Only explicit registry declarations
    // are considered active.
    // =========================================================================
}
