use std::{env, fs, path::PathBuf};
use std::path::Path;
use regex::Regex;

fn main() {
    // -------------------------------------------------------------------------
    // Cargo build-script output directory.
    //
    // Generated files must live in OUT_DIR rather than inside src/.
    // This keeps the source tree user-owned and prevents build.rs from
    // modifying committed source files during a normal cargo build.
    // -------------------------------------------------------------------------
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR is not set"));

    // =========================================================================
    // ---------------------------------------------
    //|          migration                         |
    // ---------------------------------------------
    // =========================================================================
    //
    // `registry.rs` is the single source of truth for enabled migrations.
    //
    // Example:
    //
    //     migration!(m_2025_01_15_1945_create_todos);
    //     migration!(m_2025_01_16_1030_create_users);
    //
    // Commenting out a declaration intentionally disables that migration.
    // build.rs never scans the filesystem to infer which migrations are active.
    //
    // The file is included into this function so `migration!` can simply push
    // the declared identifier into a normal Vec. This lets Rust's own parser
    // handle the source syntax; no regex, custom parser, or syn dependency is
    // required here.
    // -------------------------------------------------------------------------

    let mut migrations: Vec<&'static str> = Vec::new();

    let mut structs: Vec<&'static str> = Vec::new();
    macro_rules! migration {
        ($name:ident, $struct_name:ident) => {{
            migrations.push(stringify!($name));
            structs.push(stringify!($struct_name));
        }};
    }

    {
        include!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/src/migrations/registry.rs"
        ));
    }

    // Migration filenames contain a timestamp, so lexical ordering gives us
    // deterministic migration execution order regardless of declaration order
    // in registry.rs.
    migrations.sort_unstable();

    let mut generated = String::from(
        "// @generated by build.rs\n\
         //\n\
         // DO NOT EDIT.\n\
         //\n\
         // To add, remove, or disable migrations, edit:\n\
         //     src/migrations/registry.rs\n\
         //\n\
         // This file is generated automatically during the Cargo build.\n\
         \n",
    );

    // generated.push_str("use crate::migrator::Migration;\n\n");
    for migration in &migrations {
        let path = format!("{}/src/migrations/{}.rs", manifest_dir, migration);

        generated.push_str(format!("#[path = r\"{}\"]\n", path).as_str());
        generated.push_str(&format!("pub mod {};\n", migration));
    }

    generated.push_str(
        "\n\
         pub fn get_all_migrations() -> Vec<Box<dyn crate::migrator::Migration>> {\n\
         \tvec![\n",
    );

    for (index, migration) in migrations.iter().enumerate() {
        let current_struct = structs.get(index).unwrap();
        generated.push_str(&format!(
            "\t\tBox::new({}::{} ),\n",
            migration, current_struct
        ));
    }

    generated.push_str(
        "\t]\n\
         }\n",
    );

    fs::write(out_dir.join("migrations_generated.rs"), generated)
        .expect("failed to write generated migrations");

    // Only rerun this build script when the migration registry changes.
    println!("cargo:rerun-if-changed=src/migrations/registry.rs");

    // =========================================================================
    // ---------------------------------------------
    //|          seeder                            |
    // ---------------------------------------------
    // =========================================================================
    //
    // Seeder generation follows the pattern :
    //  src/seeders/
    //      ├── test_seeder.rs -> TestSeeder
    //      ├── todo_seeder.rs -> TodoSeeder
    //      └── user_seeder.rs -> UserSeeder
    //
    //    Generate this pattern:
    //
    //    use crate::seeders::todo_seeder::TodoSeeder;
    //    use crate::seeders::user_seeder::UserSeeder;
    //    match class.as_str() {
    //             "TodoSeeder" => {
    //             run_seeder(class.as_str(), TodoSeeder::run()).await?;
    //         },
    //         "UserSeeder" => {
    //             run_seeder(class.as_str(), UserSeeder::run()).await?;
    //         },
    //
    //        _ => {
    //               title(TitleKind::Error, &format!("Class not found: {{}}", class));
    //        }
    //     }
    // The generated output should be written to:
    //
    //     $OUT_DIR/generated_seeders.rs
    //     $OUT_DIR/generated_seeders_import.rs
    //
    // Keep this section independent from migrations so each registry remains
    // explicit and independently controllable by the developer.
    // =========================================================================

    // Get the root directory of the current Cargo package.
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    // Get Cargo's output directory.
    let out_dir = env::var("OUT_DIR").unwrap();

    // Point to the directory containing the seeders.
    let seeders_dir = Path::new(&manifest_dir).join("src/seeders");

    // Match structs whose name ends with "Seeder".
    let struct_regex =
        Regex::new(r"\bstruct\s+([A-Za-z_][A-Za-z0-9_]*Seeder)\b").unwrap();

    let mut imports = String::new();
    let mut match_arms = String::new();

    imports.push_str("// @generated by macros-core/build.rs — DO NOT EDIT MANUALLY\n");
    imports.push_str("//\n");

    for entry in fs::read_dir(&seeders_dir).unwrap() {
        let path = entry.unwrap().path();

        // Only process Rust source files.
        if path.extension().and_then(|ext| ext.to_str()) != Some("rs") {
            continue;
        }

        // Read the source code of the seeder file.
        let source = fs::read_to_string(&path).unwrap();

        let module_name = path
            .file_stem()
            .unwrap()
            .to_string_lossy();

        // Find all Seeder structs in this file.
        for captures in struct_regex.captures_iter(&source) {
            let struct_name = &captures[1];

            // ignore DatabaseSeeder
            if struct_name == "DatabaseSeeder" {
                continue;
            }
            // Generate the import for this Seeder.
            imports.push_str(&format!(
                "use crate::seeders::{module_name}::{struct_name};\n"
            ));

            // Generate the match arm for this Seeder.
            match_arms.push_str(&format!(
                r#"        "{struct_name}" => {{
            run_seeder(class.as_str(), {struct_name}::run()).await?;
        }},
"#,
            ));
        }
    }

    // Generate the final Rust source code.
    let generated = format!(
        r#"
        // @generated by database/build.rs — DO NOT EDIT MANUALLY
        //
    match class.as_str() {{
    {match_arms}
            _ => {{
                title(TitleKind::Error, &format!("Class not found: {{}}", class));
            }}
    }}
"#,
    );

    // Write the generated code into OUT_DIR.
    let output_path = Path::new(&out_dir).join("generated_seeders.rs");

    fs::write(output_path, generated).unwrap();

    // Write the generated import into OUT_DIR.
    let output_path = Path::new(&out_dir).join("generated_seeders_import.rs");

    fs::write(output_path, imports).unwrap();

    // Tell Cargo to rerun build.rs when the seeders change.
    println!("cargo:rerun-if-changed={}", seeders_dir.display());

    // =========================================================================
    // ---------------------------------------------
    //|          factory                            |
    // ---------------------------------------------
    // =========================================================================
    //
    // =========================================================================
}