// this seeder generated by artisan


use anyhow::{anyhow, Result};

pub struct TodoSeeder;

impl TodoSeeder {
    pub async fn run() -> Result<bool> {

        let success = true;

        if !success {
            return Err(anyhow!("Todo seeder failed"));
        }

        Ok(true)
    }
}
