[package]
name = "integration-tests"
version = "0.1.0"
edition = "2024"

[dependencies]
rustavel-core = { path = "../core" }
macros= {path = "../macros"}
macros-core= {path = "../macros-core"}
serde.workspace = true
time.workspace = true
tokio.workspace = true
axum.workspace = true
serde_json.workspace = true